### ISSUE TITLE
Failed on try login with Facebook

### ISSUE THREAD

**Issue by eduardoguilarducci** [CloudRail/cloudrail-si-xamarin-ios-sdk#2]
Im trying to make a login call on Facebook with Cloud Rail, but it's not working.

The error occur on GetFullname() method.

I've tried againts 3 diferent versions of Facebook API:

**v2.9:** 

I get the exception "API calls from the server require an appsecret_proof argument", even when the option is set to false (see prints attached).
<img width="458" alt="call_v2 9" src="https://user-images.githubusercontent.com/1053355/40623156-c989af1c-627b-11e8-9632-6087e4671bb4.png">
<img width="962" alt="screen shot 2018-05-28 at 13 32 38" src="https://user-images.githubusercontent.com/1053355/40623157-c9a92f36-627b-11e8-96e7-9f45e52d0b72.png">
<img width="962" alt="v2 9_option" src="https://user-images.githubusercontent.com/1053355/40623168-dd7afbb6-627b-11e8-8925-e39a69e0aaec.png">

**I've tried change the API version to 2.10 or Higher or 3.0, the i got another exception:**

<img width="458" alt="call_v3 0" src="https://user-images.githubusercontent.com/1053355/40623180-f2abba2a-627b-11e8-93c6-faa107a19fcd.png">
<img width="977" alt="screen shot 2018-05-28 at 13 28 30" src="https://user-images.githubusercontent.com/1053355/40623181-f2c98122-627b-11e8-811a-79e4aa7a5079.png">
<img width="963" alt="screen shot 2018-05-28 at 13 29 51" src="https://user-images.githubusercontent.com/1053355/40623182-f2e7bade-627b-11e8-8ce1-58d9266a54db.png">

There are that Im doing wrong?

Thank you

**Comment by mujtabaalamcr** [comment]
@eduardoguilarducci I was able to run the sample application using v2.10. Make sure all other options are off in the Advance settings besides the ones for Age restrictions. 
In the Facebook login settings have the settings shown below with the URL as: 
https://www.cloudrailauth.com/auth

![screen shot 2018-05-29 at 10 26 01](https://user-images.githubusercontent.com/29122716/40647038-2f0db22a-632b-11e8-835d-6b5d6f6025a7.png)

**Comment by eduardoguilarducci** [comment]
Hello @mujtabaalamcr and @fel-cesar 
Thank you very much! 

I changed the settings on my facebook app and everything is working now.

Thank you again
