### ISSUE TITLE
Xamarin iOS Cloud Storage doesn't work.

### ISSUE THREAD

**Issue by unamed000** [CloudRail/cloudrail-si-xamarin-ios-sdk#3]
Hi.

I’ve tried this example but it’s not working on simulator iPhone X 11.4

After i login for Google Drive or One Drive, the IndicatorActivity still spinning and nothing is showing? Look like the problem is in the GetRootFilesFolders in CloudStorageViewController.cs

**Comment by ljmyz** [comment]
Hi, same problem here.
Despite of the fix, it seem's that it is still not working with the version 1.2.19.

**Comment by ljmyz** [comment]
Working with 1.2.20, thank you.
